// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureApp.Data;

#nullable disable

namespace SecureApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207163525_AddAbwesenheiten")]
    partial class AddAbwesenheiten
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("SecureApp.Models.Abwesenheit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bemerkung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Bis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grund")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MitarbeiterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Von")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MitarbeiterId");

                    b.ToTable("Abwesenheiten");
                });

            modelBuilder.Entity("SecureApp.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Funktion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Land")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .HasColumnType("TEXT");

                    b.Property<string>("PLZ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Passwort")
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("SecureApp.Models.Abwesenheit", b =>
                {
                    b.HasOne("SecureApp.Models.Mitarbeiter", "Mitarbeiter")
                        .WithMany("Abwesenheiten")
                        .HasForeignKey("MitarbeiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mitarbeiter");
                });

            modelBuilder.Entity("SecureApp.Models.Mitarbeiter", b =>
                {
                    b.Navigation("Abwesenheiten");
                });
#pragma warning restore 612, 618
        }
    }
}
